
tokenizer: wikitext_split
detector: segment_matcher


tokenizers:
  wikitext_split:
    class: deltas.tokenizers.WikitextSplit

detectors:
  segment_matcher:
    class: deltas.detectors.SegmentMatcher
    segmenter: western_psw

segmenters:
  western_psw:
    class: deltas.segmenters.ParagraphsSentencesAndWhitespace
    whitespace: "[\\r\\n\\t\\ ]+"
    paragraph_split: "[\\t\\ \\r]*[\n][\\t\\ \\r]*[\n][\\t\\ \\r]*"
    sentence_end: "[.?!]+"
    min_sentence: 5
