
tokenizer: deltas.tokenizers.wikitext_split
detector: segment_matcher

detectors:
  segment_matcher:
    class: deltas.detectors.SegmentMatcher
    segmenter: western_psw

segmenters:
  western_psw:
    class: deltas.segmenters.ParagraphsSentencesAndWhitespace
